# Generated by Django 5.1.1 on 2025-04-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0002_memberprofile_membership_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'permissions': [('can_view_pending_applications', 'Can view pending applications'), ('can_approve_member', 'Can approve member applications'), ('can_view_approved_members', 'Can view approved members'), ('can_update_member_profile', 'Can update member profile')]},
        ),
    ]
