# Generated by Django 5.1.1 on 2025-05-12 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from uuid import uuid4

def generate_uuids(apps, schema_editor):
    LoanCategory = apps.get_model('gracecoop', 'LoanCategory')
    for obj in LoanCategory.objects.all():
        obj.uuid = uuid4()
        obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0004_user_is_2fa_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loancategory',
            options={'permissions': [('can_create_loan_category', 'Can create loan category'), ('can_edit_loan_category', 'Can edit loan category'), ('can_delete_loan_category', 'Can delete loan category')]},
        ),
     
        migrations.AddField(
            model_name='loancategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='grace_period_months',
            field=models.PositiveIntegerField(default=0, help_text='Number of months after loan period expiry for grace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancategory',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest rate as a percentage (e.g., 5.5%)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancategory',
            name='loan_period_months',
            field=models.PositiveIntegerField(default=0, help_text='Number of months loan is repayable from disbursement date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='uuid',
            field=models.UUIDField(null=True, unique=True, editable=False),
        ),
        migrations.RunPython(generate_uuids),
        migrations.AlterField(
            model_name='loancategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
