# Generated by Django 5.1.1 on 2025-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0007_loanapplication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
