# Generated by Django 5.1.1 on 2025-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0008_loan_repayment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_repayment_months',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of months the loan will be repaid over', null=True),
        ),
    ]
