# Generated by Django 5.1.1 on 2025-05-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0009_loan_total_repayment_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_period_months',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gracecoop.loancategory'),
        ),
    ]
