# Generated by Django 5.1.1 on 2025-05-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0013_alter_memberprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='num_disbursements',
            field=models.PositiveIntegerField(blank=True, help_text='Expected number of disbursements', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_disbursement',
            field=models.BooleanField(default=False, help_text='Is there more disbursement to be made?'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('partially_disbursed', 'Partially Disbursed'), ('paid', 'Paid'), ('grace_applied', 'Grace Period Applied')], default='pending', max_length=20),
        ),
    ]
