# Generated by Django 5.1.1 on 2025-05-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0014_loan_num_disbursements_loan_remaining_disbursement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={},
        ),
    ]
