# Generated by Django 5.1.1 on 2025-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0015_alter_memberprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
