# Generated by Django 5.1.1 on 2025-05-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0017_loanrepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gracecoop.disbursementlog')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='gracecoop.loan')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
