# Generated by Django 5.1.1 on 2025-05-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0018_loanrepaymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='scheduled_installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='gracecoop.loanrepaymentschedule'),
        ),
    ]
