# Generated by Django 5.1.1 on 2025-05-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0019_loanrepayment_scheduled_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='has_interest_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
