# Generated by Django 5.1.1 on 2025-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0020_loan_has_interest_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
