# Generated by Django 5.1.1 on 2025-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0021_alter_loanrepayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Short code for reference generation (e.g., BIZ, EDU, AGR)', max_length=10, null=True, unique=True),
        ),
    ]
