# Generated by Django 5.1.1 on 2025-05-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0022_loan_reference_loancategory_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_shares_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('development_levy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cooperative Configuration',
                'verbose_name_plural': 'Cooperative Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-approved_at'], 'permissions': [('can_approve_loan', 'Can Approve Loan'), ('can_delete_loan', 'Can Delete Loan'), ('can_disburse_loan', 'Can Disburse Loan'), ('can_approve_grace_period', 'Can Approve Grace Period')]},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterModelOptions(
            name='loancategory',
            options={'ordering': ['name'], 'permissions': [('can_create_loan_category', 'Can create loan category'), ('can_edit_loan_category', 'Can edit loan category'), ('can_delete_loan_category', 'Can delete loan category')]},
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='applied_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_members', to='gracecoop.cooperativeconfig'),
        ),
        migrations.CreateModel(
            name='Levy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levies', to='gracecoop.memberprofile')),
            ],
        ),
    ]
