# Generated by Django 5.1.1 on 2025-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0024_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payoff',
            field=models.BooleanField(default=False),
        ),
    ]
