# Generated by Django 5.1.1 on 2025-06-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0025_payment_payoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
