# Generated by Django 5.1.1 on 2025-06-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0026_payment_source_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
