# Generated by Django 5.1.1 on 2025-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0027_loanrepayment_source_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='repayment_applied',
            field=models.BooleanField(default=False),
        ),
    ]
