# Generated by Django 5.1.1 on 2025-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0028_payment_repayment_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativeconfig',
            name='max_monthly_levy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperativeconfig',
            name='max_monthly_shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperativeconfig',
            name='min_monthly_levy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperativeconfig',
            name='min_monthly_shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
