# Generated by Django 5.1.1 on 2025-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0029_cooperativeconfig_max_monthly_levy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativeconfig',
            name='enforce_monthly_levy',
            field=models.BooleanField(default=False),
        ),
    ]
