# Generated by Django 5.1.1 on 2025-06-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0030_cooperativeconfig_enforce_monthly_levy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperativeconfig',
            old_name='max_monthly_shares',
            new_name='max_contribution_amount',
        ),
        migrations.RenameField(
            model_name='cooperativeconfig',
            old_name='min_monthly_shares',
            new_name='min_contribution_amount',
        ),
    ]
