# Generated by Django 5.1.1 on 2025-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0031_rename_max_monthly_shares_cooperativeconfig_max_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='levy',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
