# Generated by Django 5.1.1 on 2025-06-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0032_contribution_source_reference_levy_source_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='has_paid_contribution',
        ),
    ]
