# Generated by Django 5.1.1 on 2025-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0033_remove_memberprofile_has_paid_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
