# Generated by Django 5.1.1 on 2025-06-27 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0034_memberprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
