# Generated by Django 5.1.1 on 2025-06-28 21:59

from django.db import migrations
import uuid

def populate_tokens(apps, schema_editor):
    MemberProfile = apps.get_model('gracecoop', 'MemberProfile')
    for profile in MemberProfile.objects.filter(email_verification_token__isnull=True):
        profile.email_verification_token = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0035_alter_memberprofile_email_verification_token'),
    ]

    operations = [
        migrations.RunPython(populate_tokens),
    ]
