# Generated by Django 5.1.1 on 2025-07-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0036_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementlog',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='disbursement_receipts/'),
        ),
        migrations.AddField(
            model_name='disbursementlog',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gracecoop.memberprofile'),
        ),
    ]
