# Generated by Django 5.1.1 on 2025-06-28 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0036_populate_email_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
