# Generated by Django 5.1.1 on 2025-07-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0037_disbursementlog_receipt_disbursementlog_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementlog',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
