# Generated by Django 5.1.1 on 2025-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0038_disbursementlog_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancategory',
            name='grace_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate as a percentage during grace period (e.g. 8.5%)', max_digits=5, null=True),
        ),
    ]
