# Generated by Django 5.1.1 on 2025-07-07 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0039_loancategory_grace_interest_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'permissions': [('can_view_reports', 'Can view and generate reports')]},
        ),
        migrations.AlterField(
            model_name='disbursementlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='principal_component',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
