# Generated by Django 5.1.1 on 2025-07-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0042_loanapplication_rejection_reason_loanguarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan', to='gracecoop.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantors', to='gracecoop.loan'),
        ),
    ]
