# Generated by Django 5.1.1 on 2025-07-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0043_loan_application_loanguarantor_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanguarantor',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='gracecoop.loan'),
        ),
    ]
