# Generated by Django 5.1.1 on 2025-07-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0044_alter_loanguarantor_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanguarantor',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='consent_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
