# Generated by Django 5.1.1 on 2025-07-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0045_loanguarantor_consent_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanguarantor',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='loanguarantor',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loanguarantor',
            old_name='consent_date',
            new_name='response_date',
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
