# Generated by Django 5.1.1 on 2025-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0046_alter_loanguarantor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='next_of_kin_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Pst.', 'Pst.'), ('Rev.', 'Rev.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Alh.', 'Alh.')], max_length=10),
        ),
    ]
