# Generated by Django 5.1.1 on 2025-07-26 20:00

import django.core.validators
import django.db.models.deletion
import gracecoop.models.member_doc
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0047_memberprofile_gender_memberprofile_next_of_kin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('passport', 'International Passport'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('salary_slip', 'Salary Slip'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to=gracecoop.models.member_doc.document_upload_path, validators=[gracecoop.models.member_doc.validate_document_file, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gracecoop.memberprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('passport', 'International Passport'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('salary_slip', 'Salary Slip'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('message', models.TextField(help_text='Message to member explaining why document is needed')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='gracecoop.memberprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('member', 'document_type', 'status')},
            },
        ),
    ]
