# Generated by Django 5.1.1 on 2025-07-28 13:31

import django.core.validators
import gracecoop.models.member_doc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracecoop', '0048_memberdocument_documentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=gracecoop.models.member_doc.document_upload_path, validators=[gracecoop.models.member_doc.validate_document_file, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
